### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by virgorasion** [bgd-point/point-app-test#85]
![laravel erp error](https://user-images.githubusercontent.com/31560585/32030129-25108376-ba23-11e7-963d-4e20084394e4.PNG)
![git pull](https://user-images.githubusercontent.com/31560585/32030132-254b4736-ba23-11e7-91da-314addf1d6fa.PNG)

Pak bisa tolong betulin errornya ini ?
saya sudah cari-cari di google tapi masih gk ngerti

**Comment by martiendt** [comment]
itu blm seeding databasenya, pakai command ‘php artisan dev:reset-database’

**Comment by virgorasion** [comment]
Sekarang udah bisa kebuka pak makasih

Pada tanggal 26 Okt 2017 7.05 PM, "Martien Dermawan Tanama" <
notifications@github.com> menulis:
