### ISSUE TITLE
do not open point-app-test

### ISSUE THREAD

**Issue by yogaap24** [bgd-point/point-app-test#86]
Saya tidak bisa membukanya padahal pada homestade.yaml dan hosts nya sudah saya sama kan dan sudah mengarah direktori pada folder Homestead yang saya buat saat buat namun saat mengakses hasil nya selalu mercusuar. terima kasih

**Comment by martiendt** [comment]
ini tidak ada hubungannya dengan app.

* note check status homestead nya sudah run atau belum

**Comment by yogaap24** [comment]
Sudah Pak tapi Pas buka site Yang sesuai yaml Dan host selalu gak bisa

Jumat, 27 Oktober 2017, Martien Dermawan Tanama <notifications@github.com>
menulis:
